export const CHANGE_NAV = 'CHANGE_NAV';
export const IS_LODING = 'IS_LODING';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
